export const TRACK_CELLS = [
	[   0,   0, 'trk-finish',               16 ],
	[   1,   0, 'trk-straight',             16 ],
	[   4,  -2, 'trk-straight',             16 ],
	[   3,  -2, 'trk-corner-1x1',           10 ],
	[   3,  -3, 'trk-corner-1x1',           16 ],
	[   4,  -3, 'trk-straight',             16 ],
	[   5,  -3, 'trk-corner-1x1',           22 ],
	[   5,  -4, 'trk-corner-1x1',            0 ],
	[  -3,  -4, 'trk-corner-1x1',           16 ],
	[  -3,  -3, 'trk-corner-1x1',           22 ],
	[  -4,  -3, 'trk-corner-1x1',           16 ],
	[  -4,  -2, 'trk-corner-1x1',           22 ],
	[  -5,  -2, 'trk-corner-1x1',           16 ],
	[  -5,  -1, 'trk-straight',              0 ],
	[  -5,   0, 'trk-straight',              0 ],
	[  -5,   1, 'trk-corner-1x1',           10 ],
	[  -4,   1, 'trk-corner-1x1',            0 ],
	[  -4,   2, 'trk-straight',              0 ],
	[  -4,   3, 'trk-corner-1x1',           10 ],
	[  -3,   3, 'trk-corner-1x1',            0 ],
	[  -3,   4, 'trk-corner-1x1',           10 ],
	[  -2,   4, 'trk-straight',             16 ],
	[  -1,   4, 'trk-corner-1x1',           22 ],
	[  -1,   3, 'trk-tunnel-entry',          0 ],
	[  -2,  -4, 'trk-jump-long',            16 ],
	[   1,  -4, 'trk-jump-long',            16 ],
	[  -1,  -4, 'trk-straight',             16 ],
	[   0,  -4, 'trk-straight',             16 ],
	[   2,  -4, 'trk-straight',             16 ],
	[   3,  -4, 'trk-straight',             16 ],
	[   4,  -4, 'trk-straight',             16 ],
	[  -1,   2, 'trk-straight',             10 ],
	[  -1,   1, 'trk-corner-1x1',            0 ],
	[  -2,   1, 'trk-straight',             16 ],
	[  -3,   1, 'trk-corner-1x1',           10 ],
	[  -3,   0, 'trk-corner-1x1',           16 ],
	[  -2,   0, 'trk-straight',             16 ],
	[   2,   0, 'trk-straight',             22 ],
	[   3,   0, 'trk-ramp-down-5',          16 ],
	[   4,   0, 'trk-elev-5',               16, { fullElevation: 14 } ],
	[   5,   0, 'trk-straight',             16, { fullElevation: 14 } ],
	[   6,   0, 'trk-straight',             16, { fullElevation: 14 } ],
	[   7,   0, 'trk-ramp-up-5',            22 ],
	[   8,   0, 'trk-straight',             22 ],
	[   9,  -3, 'trk-straight',             10 ],
	[   9,  -2, 'trk-corner-1x1',           22 ],
	[   8,  -2, 'trk-tunnel-entry',         22 ],
	[   7,  -2, 'trk-tunnel-mid',           22 ],
	[   6,  -2, 'trk-tunnel-exit',          22 ],
	[   5,  -2, 'trk-straight',             22 ],
	[   9,   0, 'trk-straight',             16 ],
	[  10,   0, 'trk-straight',             22 ],
	[  11,   0, 'trk-straight',             22 ],
	[  12,   0, 'trk-straight',             22 ],
	[  11,  -5, 'trk-straight',             22 ],
	[  12,  -5, 'trk-straight',             22 ],
	[  14,  -1, 'trk-curve-3x3-wide-l',    16 ],
	[  14,  -4, 'trk-curve-3x3-l',         10 ],
	[   9,  -5, 'trk-corner-1x1',           16 ],
	[   9,  -4, 'trk-straight',             10 ],
	[  10,  -5, 'trk-straight',             22 ],
];

export const DECO_CELLS = [
	[ -8, -9, 'decoration-buildings-1', 0 ], [ -7, -9, 'decoration-buildings-2', 0 ],
	[ -6, -9, 'decoration-buildings-1', 0 ], [ -5, -9, 'decoration-buildings-2', 0 ],
	[ -4, -9, 'decoration-buildings-1', 0 ], [ -3, -9, 'decoration-buildings-2', 0 ],
	[ -2, -9, 'decoration-buildings-1', 0 ], [ -1, -9, 'decoration-buildings-2', 0 ],
	[  0, -9, 'decoration-buildings-1', 0 ], [  1, -9, 'decoration-buildings-2', 0 ],
	[  2, -9, 'decoration-buildings-1', 0 ],
	[ -8, -8, 'decoration-buildings-2', 0 ], [ -7, -8, 'decoration-buildings-1', 0 ],
	[ -6, -8, 'decoration-buildings-2', 0 ], [ -5, -8, 'decoration-buildings-1', 0 ],
	[ -4, -8, 'decoration-buildings-2', 0 ], [ -3, -8, 'decoration-buildings-1', 0 ],
	[ -2, -8, 'decoration-buildings-2', 0 ], [ -1, -8, 'decoration-buildings-1', 0 ],
	[  0, -8, 'decoration-buildings-2', 0 ], [  1, -8, 'decoration-buildings-1', 0 ],
	[  2, -8, 'decoration-buildings-2', 0 ],
	[ -8, -7, 'decoration-buildings-1', 0 ], [ -7, -7, 'decoration-buildings-2', 0 ],
	[ -6, -7, 'decoration-buildings-1', 0 ], [ -5, -7, 'decoration-buildings-2', 0 ],
	[ -4, -7, 'decoration-buildings-1', 0 ], [ -3, -7, 'decoration-buildings-2', 0 ],
	[ -2, -7, 'decoration-buildings-1', 0 ], [ -1, -7, 'decoration-buildings-2', 0 ],
	[  0, -7, 'decoration-buildings-1', 0 ], [  1, -7, 'decoration-buildings-2', 0 ],
	[  2, -7, 'decoration-buildings-1', 0 ],
	[ -8, -6, 'decoration-buildings-2', 0 ], [ -7, -6, 'decoration-buildings-1', 0 ],
	[ -6, -6, 'decoration-buildings-2', 0 ], [ -5, -6, 'decoration-buildings-1', 0 ],
	[ -4, -6, 'decoration-buildings-2', 0 ], [ -3, -6, 'decoration-empty-night', 0 ],
	[ -2, -6, 'decoration-empty-night', 0 ],  [ -1, -6, 'decoration-empty-night', 0 ],
	[  0, -6, 'decoration-empty-night', 0 ],  [  1, -6, 'decoration-buildings-1', 0 ],
	[  2, -6, 'decoration-buildings-2', 0 ],
	[ -8, -5, 'decoration-buildings-1', 0 ], [ -7, -5, 'decoration-buildings-2', 0 ],
	[ -6, -5, 'decoration-buildings-1', 0 ], [ -5, -5, 'decoration-buildings-2', 0 ],
	[ -4, -5, 'decoration-empty-night', 0 ],  [ -3, -5, 'decoration-empty-night', 0 ],
	[ -2, -5, 'decoration-empty-night', 0 ],  [ -1, -5, 'decoration-empty-night', 0 ],
	[  0, -5, 'decoration-empty-night', 0 ],  [  1, -5, 'decoration-buildings-1', 0 ],
	[  2, -5, 'decoration-buildings-2', 0 ],
	[ -8, -4, 'decoration-buildings-1', 0 ], [ -7, -4, 'decoration-buildings-2', 0 ],
	[ -6, -4, 'decoration-buildings-1', 0 ], [ -5, -4, 'decoration-buildings-2', 0 ],
	[ -4, -4, 'decoration-empty-night', 0 ],
	[  1, -4, 'decoration-buildings-1', 0 ],
	[  2, -4, 'decoration-buildings-2', 0 ],
	[ -8, -3, 'decoration-buildings-2', 0 ], [ -7, -3, 'decoration-buildings-1', 0 ],
	[ -6, -3, 'decoration-buildings-2', 0 ], [ -5, -3, 'decoration-buildings-1', 0 ],
	[ -4, -3, 'decoration-empty-night', 0 ],
	[  1, -3, 'decoration-buildings-2', 0 ],
	[  2, -3, 'decoration-buildings-1', 0 ],
	[ -8, -2, 'decoration-buildings-1', 0 ], [ -7, -2, 'decoration-buildings-2', 0 ],
	[ -6, -2, 'decoration-buildings-1', 0 ], [ -5, -2, 'decoration-buildings-2', 0 ],
	[  1, -2, 'decoration-buildings-1', 0 ],
	[  2, -2, 'decoration-buildings-2', 0 ],
	[ -8, -1, 'decoration-buildings-2', 0 ], [ -7, -1, 'decoration-buildings-1', 0 ],
	[ -6, -1, 'decoration-buildings-2', 0 ], [ -5, -1, 'decoration-buildings-1', 0 ],
	[ -4, -1, 'decoration-empty-night', 0 ],  [ -1, -1, 'decoration-empty-night', 0 ],
	[  1, -1, 'decoration-buildings-2', 0 ],
	[  2, -1, 'decoration-buildings-1', 0 ],
	[ -8,  0, 'decoration-buildings-1', 0 ], [ -7,  0, 'decoration-buildings-2', 0 ],
	[ -6,  0, 'decoration-buildings-1', 0 ], [ -5,  0, 'decoration-buildings-2', 0 ],
	[ -4,  0, 'decoration-empty-night', 0 ],  [ -3,  0, 'decoration-empty-night', 0 ],
	[ -1,  0, 'decoration-empty-night', 0 ],
	[  1,  0, 'decoration-buildings-1', 0 ],
	[  2,  0, 'decoration-buildings-2', 0 ],
	[ -8,  1, 'decoration-buildings-2', 0 ], [ -7,  1, 'decoration-buildings-1', 0 ],
	[ -6,  1, 'decoration-buildings-2', 0 ], [ -5,  1, 'decoration-buildings-1', 0 ],
	[ -4,  1, 'decoration-empty-night', 0 ],  [ -3,  1, 'decoration-empty-night', 0 ],
	[  1,  1, 'decoration-buildings-2', 0 ],
	[  2,  1, 'decoration-buildings-1', 0 ],
	[ -8,  2, 'decoration-buildings-1', 0 ], [ -7,  2, 'decoration-buildings-2', 0 ],
	[ -6,  2, 'decoration-buildings-1', 0 ], [ -5,  2, 'decoration-buildings-2', 0 ],
	[ -4,  2, 'decoration-empty-night', 0 ],  [ -3,  2, 'decoration-empty-night', 0 ],
	[  1,  2, 'decoration-buildings-1', 0 ],
	[  2,  2, 'decoration-buildings-2', 0 ],
	[ -8,  3, 'decoration-buildings-2', 0 ], [ -7,  3, 'decoration-buildings-1', 0 ],
	[ -6,  3, 'decoration-buildings-2', 0 ], [ -5,  3, 'decoration-buildings-1', 0 ],
	[ -4,  3, 'decoration-buildings-2', 0 ], [ -3,  3, 'decoration-buildings-1', 0 ],
	[ -2,  3, 'decoration-buildings-2', 0 ], [ -1,  3, 'decoration-buildings-1', 0 ],
	[  0,  3, 'decoration-buildings-2', 0 ], [  1,  3, 'decoration-buildings-1', 0 ],
	[  2,  3, 'decoration-buildings-2', 0 ],
	[ -8,  4, 'decoration-buildings-1', 0 ], [ -7,  4, 'decoration-buildings-2', 0 ],
	[ -6,  4, 'decoration-buildings-1', 0 ], [ -5,  4, 'decoration-buildings-2', 0 ],
	[ -4,  4, 'decoration-buildings-1', 0 ], [ -3,  4, 'decoration-buildings-2', 0 ],
	[ -2,  4, 'decoration-buildings-1', 0 ], [ -1,  4, 'decoration-buildings-2', 0 ],
	[  0,  4, 'decoration-buildings-1', 0 ], [  1,  4, 'decoration-buildings-2', 0 ],
	[  2,  4, 'decoration-buildings-1', 0 ],
];
