// ─── ElevationController ─────────────────────────────────────────────────────
// Manages elevation: raise/lower in 2.5m increments, auto-ramp generation,
// and corner elevation derivation. Supports the full -30m to +30m range.

import { ORIENT_FLIP } from './AutoTileService.js';
import { DIR_INFO } from './AutoTileService.js';
import { getElevationModelName, scanElevatedRun } from '../../ElevationUtils.js';
import { ELEV_GROUND, ELEV_STEP } from '../models/TrackProject.js';
import { TrackTile } from '../models/TrackTile.js';

const MIN_ELEV_STEP = 0;   // -30m
const MAX_ELEV_STEP = 24;  // +30m

export class ElevationController {

	constructor( project, meshFactory, eventBus ) {

		this._project = project;
		this._meshFactory = meshFactory;
		this._eventBus = eventBus;

	}

	/**
	 * Check if a cell can be elevated.
	 * @param {number} gx
	 * @param {number} gz
	 * @returns {boolean}
	 */
	canElevate( gx, gz ) {

		const cell = this._project.getTile( gx, gz );
		if ( ! cell ) return false;

		// Block auto-managed ramps (generated by elevation system)
		if ( cell.autoRamp ) return false;
		// Block invisible flank reservations
		if ( cell.finishFlank ) return false;
		// Block consumed multi-tile cells
		if ( cell._consumed ) return false;
		// Manually placed ramp tiles CAN be elevated (they're just tiles)
		// Only auto-ramps (autoRamp=true) are blocked above

		return true;

	}

	/**
	 * Raise elevation by one step (2.5m).
	 * @param {number} gx
	 * @param {number} gz
	 * @returns {number|null} Previous elevation step or null if rejected
	 */
	raiseElevation( gx, gz ) {

		if ( ! this.canElevate( gx, gz ) ) return null;

		const cell = this._project.getTile( gx, gz );
		const prev = cell.elevation;

		if ( cell.elevation >= MAX_ELEV_STEP ) return null;

		cell.elevation += 1;
		this._applyElevation( gx, gz, cell );

		this._eventBus.emit( 'elevation:changed', { gx, gz, prev, next: cell.elevation } );
		return prev;

	}

	/**
	 * Lower elevation by one step (2.5m).
	 * @param {number} gx
	 * @param {number} gz
	 * @returns {number|null} Previous elevation step or null if rejected
	 */
	lowerElevation( gx, gz ) {

		if ( ! this.canElevate( gx, gz ) ) return null;

		const cell = this._project.getTile( gx, gz );
		const prev = cell.elevation;

		if ( cell.elevation <= MIN_ELEV_STEP ) return null;

		cell.elevation -= 1;
		this._applyElevation( gx, gz, cell );

		this._eventBus.emit( 'elevation:changed', { gx, gz, prev, next: cell.elevation } );
		return prev;

	}

	/**
	 * Cycle elevation: ground → 2.5m → 5m → ground (legacy 3-level cycle).
	 * @param {number} gx
	 * @param {number} gz
	 * @returns {number|null}
	 */
	cycleElevation( gx, gz ) {

		if ( ! this.canElevate( gx, gz ) ) return null;

		const cell = this._project.getTile( gx, gz );
		const prev = cell.elevation;

		// Cycle: ground(12) → 13 → 14 → 12
		if ( cell.elevation === ELEV_GROUND ) cell.elevation = 13;
		else if ( cell.elevation === 13 ) cell.elevation = 14;
		else cell.elevation = ELEV_GROUND;

		this._applyElevation( gx, gz, cell );

		this._eventBus.emit( 'elevation:changed', { gx, gz, prev, next: cell.elevation } );
		return prev;

	}

	/**
	 * Get the elevation in meters for a step index.
	 * @param {number} step
	 * @returns {number}
	 */
	stepToMeters( step ) {

		return ( step - ELEV_GROUND ) * ELEV_STEP;

	}

	// ── Ramp management ──

	/**
	 * Recalculate ramps for the entire elevated run containing (gx, gz).
	 */
	recalculateRunRamps( gx, gz ) {

		const grid = this._project.getGrid();
		const cell = this._project.getTile( gx, gz );
		if ( ! cell ) return;

		const v3Elev = this._toV3Elev( cell.elevation );
		if ( v3Elev === 0 ) return;

		const v3Grid = this._buildV3CompatGrid();
		const run = scanElevatedRun( v3Grid, gx, gz, ( x, z ) => x + ',' + z );
		if ( run.length === 0 ) return;

		const runKeys = new Set( run.map( t => t.key ) );

		// Clear existing auto-ramps for this run
		for ( const [ rKey, rCell ] of grid ) {

			if ( rCell.autoRamp && runKeys.has( rCell.rampParent ) ) {

				rCell.autoRamp = false;
				rCell.rampParent = null;
				rCell.type = 'trk-straight';
				rCell.elevation = ELEV_GROUND;
				const [ rx, rz ] = rKey.split( ',' ).map( Number );
				this._meshFactory.createTileMesh( rx, rz, rCell );

			}

		}

		// Determine axis
		const firstCell = grid.get( run[ 0 ].key );
		const orient = firstCell.orient;
		const isNS = orient === 0 || orient === 10;
		const dx = isNS ? 0 : 1;
		const dz = isNS ? 1 : 0;

		// Place ramps at run edges
		const first = run[ 0 ];
		const last = run[ run.length - 1 ];
		const edges = [
			{ edge: first, dir: - 1, parentIdx: 0 },
			{ edge: last, dir: 1, parentIdx: run.length - 1 },
		];

		for ( const { edge, dir, parentIdx } of edges ) {

			const parentTile = run[ parentIdx ];
			const parentCell = grid.get( parentTile.key );
			const parentV3Elev = this._toV3Elev( parentCell.elevation );

			const nx = edge.gx + dx * dir;
			const nz = edge.gz + dz * dir;
			const nKey = this._project.cellKey( nx, nz );
			let nCell = grid.get( nKey );

			if ( ! nCell ) {

				nCell = new TrackTile( 'trk-straight', orient, ELEV_GROUND );
				this._project.setTile( nx, nz, nCell );

			}

			if ( nCell.elevation > ELEV_GROUND ) continue;

			const bx = nx + dx * dir;
			const bz = nz + dz * dir;
			const bCell = this._project.getTile( bx, bz );
			if ( ! bCell ) continue;

			const role = dir === 1 ? 'ramp-up' : 'ramp-down';
			const style = parentCell.rampStyle || 'steep';

			nCell.autoRamp = true;
			nCell.rampParent = parentTile.key;
			nCell.type = getElevationModelName( parentV3Elev, role, style );
			nCell.orient = orient;

			if ( role === 'ramp-up' ) {

				nCell.orient = ORIENT_FLIP[ orient ] ?? orient;

			}

			this._meshFactory.createTileMesh( nx, nz, nCell );

		}

		// Derive corner elevations
		const checked = new Set();
		for ( const tile of run ) {

			for ( const dir of DIR_INFO ) {

				const nk = this._project.cellKey( tile.gx + dir.dx, tile.gz + dir.dz );
				if ( checked.has( nk ) ) continue;
				checked.add( nk );
				this.deriveCornerElevation( tile.gx + dir.dx, tile.gz + dir.dz );

			}

		}

	}

	/**
	 * Derive elevation for a corner cell from adjacent elevated straights.
	 */
	deriveCornerElevation( gx, gz ) {

		const cell = this._project.getTile( gx, gz );
		if ( ! cell || cell.type !== 'trk-corner-1x1' ) return;

		const exits = cell.getExitMask();
		let maxElev = 0;

		for ( const dir of DIR_INFO ) {

			if ( ! ( exits & dir.bit ) ) continue;
			const nCell = this._project.getTile( gx + dir.dx, gz + dir.dz );
			if ( ! nCell ) continue;

			const nElev = this._toV3Elev( nCell.elevation );
			if ( nElev > maxElev ) maxElev = nElev;

		}

		cell._derivedElevation = maxElev;
		this._meshFactory.createTileMesh( gx, gz, cell );

	}

	/**
	 * Load-time: derive all ramps and corner elevations.
	 */
	deriveRampsFromElevation() {

		const grid = this._project.getGrid();

		// Pass 1: Clear all autoRamp cells
		for ( const [ key, cell ] of grid ) {

			if ( ! cell.autoRamp ) continue;
			cell.autoRamp = false;
			cell.rampParent = null;
			cell.type = 'trk-straight';
			cell.elevation = ELEV_GROUND;
			const [ rx, rz ] = key.split( ',' ).map( Number );
			this._meshFactory.createTileMesh( rx, rz, cell );

		}

		// Pass 2: Process each elevated run once
		const processed = new Set();

		for ( const [ key, cell ] of grid ) {

			if ( cell.elevation <= ELEV_GROUND ) continue;
			if ( cell.type === 'trk-corner-1x1' || cell.isFinish ) continue;
			if ( processed.has( key ) ) continue;

			const [ gx, gz ] = key.split( ',' ).map( Number );
			const v3Elev = this._toV3Elev( cell.elevation );

			cell.type = getElevationModelName( v3Elev, 'flat' );
			this._meshFactory.createTileMesh( gx, gz, cell );

			const v3Grid = this._buildV3CompatGrid();
			const run = scanElevatedRun( v3Grid, gx, gz, ( x, z ) => x + ',' + z );
			for ( const tile of run ) processed.add( tile.key );

			this.recalculateRunRamps( gx, gz );

		}

		// Pass 3: Corner elevations
		for ( const [ key, cell ] of grid ) {

			if ( cell.type !== 'trk-corner-1x1' ) continue;
			const [ cgx, cgz ] = key.split( ',' ).map( Number );
			this.deriveCornerElevation( cgx, cgz );

		}

	}

	// ── Private helpers ──

	/**
	 * Apply elevation change: update model type, rebuild mesh, recalculate ramps.
	 * @private
	 */
	_applyElevation( gx, gz, cell ) {

		const isStraight = cell.type === 'trk-straight' || cell.type.startsWith( 'trk-elev-' );

		if ( cell.elevation > ELEV_GROUND ) {

			if ( isStraight ) {

				// Straight tiles swap to elevated model
				const v3Elev = this._toV3Elev( cell.elevation );
				cell.type = getElevationModelName( v3Elev, 'flat' );

			}

			// All tiles: rebuild mesh at new Y position
			this._meshFactory.createTileMesh( gx, gz, cell );

			if ( isStraight ) this.recalculateRunRamps( gx, gz );

		} else if ( cell.elevation === ELEV_GROUND ) {

			if ( isStraight ) {

				cell.type = 'trk-straight';

			}

			this._meshFactory.createTileMesh( gx, gz, cell );

			// Clear orphaned ramps (only relevant for straight tiles)
			if ( isStraight ) {

				const key = this._project.cellKey( gx, gz );
				for ( const [ rKey, rCell ] of this._project.getGrid() ) {

					if ( rCell.autoRamp && rCell.rampParent === key ) {

						rCell.autoRamp = false;
						rCell.rampParent = null;
						rCell.type = 'trk-straight';
						rCell.elevation = ELEV_GROUND;
						const [ rx, rz ] = rKey.split( ',' ).map( Number );
						this._meshFactory.createTileMesh( rx, rz, rCell );

					}

				}

				for ( const dir of DIR_INFO ) {

					const nCell = this._project.getTile( gx + dir.dx, gz + dir.dz );
					if ( nCell && nCell.elevation > ELEV_GROUND ) {

						this.recalculateRunRamps( gx + dir.dx, gz + dir.dz );

					}

				}

			}

		} else {

			// Below ground (< 12) — use straight model at negative Y
			cell.type = 'trk-straight';
			this._meshFactory.createTileMesh( gx, gz, cell );

		}

	}

	/**
	 * Convert v4 elevation step to v3-style level (0, 1, or 2).
	 * Steps 13 → 1 (2.5m), steps 14+ → 2 (5m model, stacked via Y offset).
	 * @private
	 */
	_toV3Elev( step ) {

		if ( step <= ELEV_GROUND ) return 0;
		if ( step === ELEV_GROUND + 1 ) return 1;
		return 2; // 5m model, Y offset handles the rest

	}

	/**
	 * Build a v3-compatible grid for scanElevatedRun.
	 * @private
	 */
	_buildV3CompatGrid() {

		const v3Grid = new Map();

		for ( const [ key, tile ] of this._project.getGrid() ) {

			v3Grid.set( key, {
				type: tile.type,
				orient: tile.orient,
				elevation: this._toV3Elev( tile.elevation ),
				isFinish: tile.isFinish,
			} );

		}

		return v3Grid;

	}

}
